### ISSUE TITLE
It works on passkeys created in Chrome browser but fail to store in iCloud Keychain using Safari. 

### ISSUE THREAD

**Issue by hisgarden** [corbado/passkey-tutorial#1] opened 2024-01-25 17:33 UTC
I tested this out and notice this error in Safari 17.2.1. 

sql: "INSERT INTO credentials (user_id, credential_id, public_key, counter, transports) VALUES ('f04bf801-e185-4061-b233-c183d953c9cf', 'lf5E3aMz9/Z98aX/5+cotUfDfkU=', 'pQECAyYgASFYIIc7bKcJroIFbo0Mc6MhZNAglkJPKdKUoYNcHP4UZodLIlgg84z56dl8QVodbitj03Mrtlkl1po1NCWTuRxX7Aczlwo=', 0, 'internal', 'hybrid')",
app-1  |   sqlState: '21S01',
app-1  |   sqlMessage: "Column count doesn't match value count at row 1"

I think the issue is the column transports in table credentials did not consider two values returned from iCloud Keychain : internal and hybrid.  

on src/controllers/registration.ts/handleRegisterFinish function, body.response.transports is an array of strings.  It used to be one of the following: "usb", "nfc", "ble", or "internal", but recently, both "internal" and "hybrid" could be returned at the same time, causing the error above

**Comment by vincentdelitz** [comment] 2024-01-30 18:41
Thanks @hisgarden for rising this issue. I'll take a look into it!

**Comment by vincentdelitz** [comment] 2024-03-13 08:18
@hisgarden the issue is fixed with the latest update

**Closed as completed by vincentdelitz** 2024-03-13 08:18 UTC
